.catalog:
  name: MyTomcat Demo
  description: |
    (mytomcat) Catalog Demo
  version: 0.1
  minimum_rancher_version: v1.0.0
  maintainer: "Rancher-CN <rancher-cn@outlook.com>"
version: '2'
services:
  tomcat:
    scale: 1
    start_on_create: true
